"""empty message

Revision ID: 7275d7e4dee3
Revises: e041d070a60c
Create Date: 2023-08-22 04:40:35.113181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7275d7e4dee3'
down_revision: Union[str, None] = 'e041d070a60c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_url_short', table_name='url')
    op.drop_column('url', 'short')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('short', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_url_short', 'url', ['short'], unique=False)
    # ### end Alembic commands ###
