"""empty message

Revision ID: e041d070a60c
Revises: 
Create Date: 2023-08-18 03:23:14.273027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e041d070a60c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original', sa.String(), nullable=False),
    sa.Column('short', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_original'), 'url', ['original'], unique=True)
    op.create_index(op.f('ix_url_short'), 'url', ['short'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_short'), table_name='url')
    op.drop_index(op.f('ix_url_original'), table_name='url')
    op.drop_table('url')
    # ### end Alembic commands ###
